// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_Screen4);
lv_img_set_src(ui_Image5, &ui_img_logo_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 220
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 36
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,200);

ui_Button2 = ui_Button1_create(ui_Screen4);
lv_obj_set_x( ui_Button2, 0 );
lv_obj_set_y( ui_Button2, 96 );

ui_Label4 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Back");

lv_obj_add_event_cb(ui_Button2, ui_event_Button2_Button1, LV_EVENT_ALL, NULL);

}
